server.port=8082

app.crud.base-url=${CRUD_BASE_URL:http://app:8081}
app.crud.connect-timeout-ms=${CRUD_CONNECT_TIMEOUT_MS:3000}
app.crud.read-timeout-ms=${CRUD_READ_TIMEOUT_MS:5000}

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
